- name: ensure cirros image is added to glance
  glance_image: >-  
    auth_url=http://{{ controller_ip }}:5000/v3/
    copy_from={{ img_url }}
    name={{ img_name }}
    container_format=bare
    disk_format=qcow2
    state=present
    login_username=demo
    login_tenant_name=demo
    login_password={{ demo_pass }}
    region_name={{ region }}

