---
- name: Updating package list
  apt:
    update_cache: yes

- name: "Install docker prerequisites packages: apt-transport-https"
  apt: name=apt-transport-https state=present

- name: "Install docker prerequisites packages: ca-certificates"
  apt: name=ca-certificates state=present

- name: "Install docker prerequisites packages: curl"
  apt: name=curl state=present

- name: "Install docker prerequisites packages: software-properties-common"
  apt: name=software-properties-common state=present

- name: Adding Docker APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Updating package list
  apt:
      update_cache: yes

- name: Installing Docker CE 17.12
  apt:
    name: docker-ce
    state: present
